require 'semantic_logger'

require 'active_record/core_ext/string'
require 'active_record/local_storage'
require 'active_record/store/store_id'
require 'active_record/store/store_id_generator'
require 'active_record/store/abstract_store'
require 'active_record/store/local_storage_store'
require 'active_record/store/memory_store'
require 'active_record/association'
require 'active_record/collection_proxy'
require 'active_record/relation'
require 'active_record/arel'
require 'active_record/callbacks'
require 'active_record/core'
